# Generated by Django 3.2.6 on 2024-04-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklog',
            name='associated_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.invoice'),
        ),
    ]
