# Generated by Django 3.2.6 on 2024-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_booklog_associated_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_log',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='booklog',
            name='parent_book',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_log',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BillingProfile',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookLog',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
    ]
